# yaml-language-server: $schema=https://json.schemastore.org/mkdocs-1.6.json
site_name: Yandex Smart Home
site_url: https://docs.yaha-cloud.ru
repo_url: https://github.com/dext0r/yandex_smart_home

nav:
  - О компоненте: index.md
  - Особенности интеграции и УДЯ : quirks.md
  - Установка и обновление компонента: install/component.md
  - Добавление интеграции: install/integration.md
  - Настройка интеграции:
      - Способы настройки: config/getting-started.md
      - Выбор объектов для передачи: config/filter.md
      - Параметры устройств: config/entity.md
      - Режимы/функции: config/modes.md
      - Тип подключения: config/connection-type.md
      - Подключение нескольких HA: config/multi-ha.md
  - Устройства:
      - Датчики:
          - О датчиках: devices/sensor/about.md
          - Цифровые датчики: devices/sensor/float.md
          - Событийные датчики: devices/sensor/event.md
      - Освещение: devices/light.md
      - Камеры: devices/camera.md
      - Кондиционеры: devices/climate.md
      - Кнопки: devices/button.md
  - Для продвинутых:
      - Прямое подключение:
          - advanced/direct-connection/index.md
          - Дом с Алисой: advanced/direct-connection/yandex.md
          - Маруся: advanced/direct-connection/vk.md
      - Пользовательские умения:
          - О пользовательских умениях: advanced/capabilities/about.md
          - Умения "Режимы работы": advanced/capabilities/mode.md
          - Умения "Выбор из диапазона": advanced/capabilities/range.md
          - Умения "Переключатели": advanced/capabilities/toggle.md
      - События: advanced/events.md
      - Коды ошибок: advanced/error-codes.md
  - Платформы умного дома:
      - Дом с Алисой: platforms/yandex.md
      - Маруся: platforms/vk.md
  - Устранение проблем: troubleshoot.md
  - Часто задаваемые вопросы: faq.md
  - Поддерживаемые устройства: supported-devices.md
  - Обратная совместимость: breaking-changes.md
  - Рецепты: recipes.md

theme:
  name: material
  custom_dir: docs/_overrides
  language: ru
  logo: assets/logo/logo.png
  favicon: assets/logo/favicon.png
  icon:
    repo: fontawesome/brands/github
  font:
    text: PT Sans
    code: Fira Code
  palette:
    primary: light blue
    accent: indigo
  features:
    - navigation.indexes
    - navigation.tracking
    - navigation.top
    - navigation.footer
    - content.code.copy

extra:
  social:
    - icon: fontawesome/brands/telegram
      link: http://t.me/yandex_smart_home
  version:
    provider: mike

extra_css:
  - assets/extra.css

plugins:
  - search:
      lang:
        - en
        - ru

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - footnotes
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.smartsymbols
  - pymdownx.critic
